export interface TrackVideo {
  num: number;
  track: string;
  url: string;
  flips?: number;
}

export const flips: TrackVideo[] = [
  { num: 22, track: "Seekonk Speedway", url: "https://youtu.be/a1qwU1SYpYk" },
  { num: 25, track: "Wall Stadium Speedwday", url: "https://youtu.be/4i868jFmovM" },
  { num: 26, track: "Wall Stadium Speedway", url: "https://youtu.be/QvqZ5S9ngBc" },
  { num: 27, track: "Thompson Speedway Motorsports Park", url: "https://youtu.be/qnaZx0-qrx4" },
  { num: 34, track: "Texas Motor Speedway (Paved Road Course)", url: "https://youtu.be/Dw8-C4e92Rw" },
  { num: 35, track: "Albany-Saratoga Speedway", url: "https://youtu.be/dAEwz_l3EwI" },
  { num: 36, track: "Hudson Speedway", url: "https://youtu.be/zHZsYcHruVQ" },
  { num: 45, track: "Gateway Dirt Nationals", url: "https://youtu.be/xwbHto21yP8" },
  { num: 46, track: "Gateway Dirt Nationals", url: "https://youtu.be/wRqwFMZYfec" },
  { num: 47, track: "Gateway Dirt Nationals", url: "https://youtu.be/IlkOqt_bbzk" },
  { num: 53, track: "NY Exposition Center", url: "https://youtu.be/4f6jP6AI6Wk" },
  { num: 60, track: "New Egypt Speedway", url: "https://youtu.be/cxjlwA8F7H0" },
  { num: 62, track: "Bear Ridge Speedway", url: "https://youtu.be/OHRJU_4lUaU" },
  { num: 66, track: "Albany-Saratoga Speedway", url: "https://youtu.be/RXIIX3CXEwQ" },
  { num: 68, track: "Utica-Rome Speedway", url: "https://youtu.be/6wcHXTKJer8" },
  { num: 71, track: "Lebanon Valley Speedway", url: "https://youtu.be/XT38ST92vaI" },
  { num: 74, track: "Southern Iowa Speedway", url: "https://youtu.be/HAfTtnNmX44" },
  { num: 76, track: "Knoxville Raceway", url: "https://youtu.be/wiXJBXhC1KA" },
  { num: 78, track: "Knoxville Raceway", url: "https://youtu.be/l1ERU59hts8" },
  { num: 80, track: "Knoxville Raceway", url: "https://youtu.be/kPL-WRLpgA4" },
  { num: 81, track: "Knoxville Raceway", url: "https://youtu.be/7OE8wgkOSUk" },
  { num: 82, track: "Knoxville Raceway", url: "https://youtu.be/9AsCEzgjVzo" },
  { num: 84, track: "Knoxville Raceway", url: "https://youtu.be/yxeC4UQ69uQ" },
  { num: 96, track: "Gateway Dirt Nationals", url: "https://youtu.be/PkMbPpSWmcQ" },
  { num: 98, track: "Gateway Dirt Nationals", url: "https://youtu.be/ZiSB0u2Ja8Y" },
  { num: 99, track: "Gateway Dirt Nationals", url: "https://youtu.be/h3DeFT2lgak" },
  { num: 100, track: "Gateway Dirt Nationals", url: "https://youtu.be/Co1_RhnqIy0" },
  { num: 101, track: "Gateway Dirt Nationals", url: "https://youtu.be/Co1_RhnqIy0" },
  { num: 102, track: "Gateway Dirt Nationals", url: "https://youtu.be/aOvSAQdtIxs" },
  { num: 103, track: "Gateway Dirt Nationals", url: "https://youtu.be/lF0K4LKu5y4" },
  { num: 104, track: "Gateway Dirt Nationals", url: "https://youtu.be/2AJYm58_DUs" },
  { num: 105, track: "Gateway Dirt Nationals", url: "https://youtu.be/EOQzY-34EGw" },
  { num: 106, track: "Gateway Dirt Nationals", url: "https://youtu.be/5MfL6KUrT0c" },
  { num: 110, track: "PPL Center", url: "https://youtu.be/QYm0M13UMe4" },
  { num: 111, track: "PPL Center", url: "https://youtu.be/sa-2RuocU1I" },
  { num: 117, track: "William's Grove Speedway", url: "https://youtu.be/GkfpzVgc1sA" },
  { num: 119, track: "Paragon Speedway (Qualifying)", url: "https://youtu.be/ZtAHMGVi3zw" },
  { num: 120, track: "Paragon Speedway", url: "https://youtu.be/Gi7ySPGU9Yo" },
  { num: 122, track: "Paragon Speedway", url: "https://youtu.be/a-7DlDQEONY" },
  { num: 126, track: "Paragon Speedway", url: "https://youtu.be/wnRHKzCd27s" },
  { num: 127, track: "Gas City Speedway", url: "https://youtu.be/k3qEkGSfco8" },
  { num: 128, track: "Gas City Speedway (Qualifying)", url: "https://youtu.be/El7bOOZiTsc" },
  { num: 137, track: "Tri-State Speedway", url: "https://youtu.be/P7vybhmS_C8" },
  { num: 140, track: "Lawrenceburg Speedway", url: "https://youtu.be/ya80DbyekgY" },
  { num: 141, track: "Lawrenceburg Speedway", url: "https://youtu.be/ya80DbyekgY" },
  { num: 142, track: "Lawrenceburg Speedway", url: "https://youtu.be/eDJbubcf6O4" },
  { num: 145, track: "Kokomo Speedway", url: "https://youtu.be/oGbBgisv1Vg" },
  { num: 146, track: "Kokomo Speedway", url: "https://youtu.be/fTSWTfIq38I" },
  { num: 147, track: "Kokomo Speedway", url: "https://youtu.be/59k3P10lhew" },
  { num: 149, track: "Selinsgrove Speedway", url: "https://youtu.be/vHso7KvLyAM" },
  { num: 154, track: "Big Diamond Speedway", url: "https://youtu.be/bxHrYoygHOA" },
  { num: 168, track: "Kokomo Speedway (Qualifying)", url: "https://youtu.be/4g342y2U_yc" },
  { num: 169, track: "Kokomo Speedway", url: "https://youtu.be/ljLIvXk3H3M" },
  { num: 173, track: "Macon Speedway", url: "https://youtu.be/_4ObfTEetCQ" },
  { num: 174, track: "Macon Speedway", url: "https://youtu.be/VQnVaPavDXQ" },
  { num: 175, track: "Macon Speedway", url: "https://youtu.be/6CS-0CgYvcw" },
  { num: 181, track: "Bridgeport Motorsports Park", url: "https://youtu.be/4eQMtX-B1-o" },
  { num: 182, track: "Bridgeport Motorsports Park", url: "https://youtu.be/Kyebqj8-_vo" },
  { num: 183, track: "Bridgeport Motorsports Park", url: "https://youtu.be/Sh_qPdZQKCg" },
  { num: 184, track: "Bridgeport Motorsports Park", url: "https://youtu.be/JlHfEv7B9oY" },
  { num: 185, track: "Bridgeport Motorsports Park", url: "https://youtu.be/izv1GRVuTo8" },
  { num: 186, track: "Bridgeport Motorsports Park", url: "https://youtu.be/izv1GRVuTo8" },
  { num: 187, track: "Bridgeport Motorsports Park", url: "https://youtu.be/b-1EX7Po_zU" },
  { num: 188, track: "Bristol Motor Speedway (Dirt) (Qualifying)", url: "https://youtu.be/X5yqCbfS1Nk" },
  { num: 189, track: "Bristol Motor Speedway (Dirt)", url: "https://youtu.be/0PcfP55VBoE" },
  { num: 190, track: "Bristol Motor Speedway (Dirt)", url: "https://youtu.be/GhACS21sYOA" },
  { num: 191, track: "Bristol Motor Speedway (Dirt)", url: "https://youtu.be/GC976Robl8c" },
  { num: 192, track: "Fonda Speedway", url: "https://youtu.be/Tco1oKcDPPU" },
  { num: 196, track: "Bear Ridge Speedway", url: "https://youtu.be/204K7ftxQBU" },
  { num: 201, track: "Bear Ridge Speedway", url: "https://youtu.be/geenij29KrQ" },
  { num: 204, track: "Action Track USA", url: "https://youtu.be/p2Y1FQSk_Dw" },
  { num: 205, track: "Action Track USA", url: "https://youtu.be/S6f-GEJgMv0" },
  { num: 206, track: "Action Track USA", url: "https://youtu.be/fzVFyxTTeGw" },
  { num: 207, track: "Action Track USA", url: "https://youtu.be/9ZKbhLsyXfs" },
  { num: 210, track: "Wayne County Speedway", url: "https://youtu.be/YYPgneW3F58" },
  { num: 211, track: "Wayne County Speedway", url: "https://youtu.be/Gxs7p3WC2zA" },
  { num: 213, track: "Bridgeport Motorsports Park", url: "https://youtu.be/QGyXF3j39S4" },
  { num: 214, track: "Bridgeport Motorsports Park", url: "https://youtu.be/QGyXF3j39S4" },
  { num: 217, track: "William's Grove Speedway (Qualifying)", url: "https://youtu.be/Lpuj0Ia_TIo" },
  { num: 218, track: "Bloomsburg Fairgrounds Speedway (Qualifying)", url: "https://youtu.be/nfz0ujnp0X4" },
  { num: 219, track: "Bloomsburg Fairgrounds Speedway (Qualifying)", url: "https://youtu.be/68zfHnb2KA8" },
  { num: 221, track: "ERX", url: "https://youtu.be/pZ-7Z11FQAQ" },
  { num: 226, track: "Mason City Motor Speedway", url: "https://youtu.be/NVmvUxBHvnw" },
  { num: 232, track: "Grandview Speedway", url: "https://youtu.be/enqjq7CSbIA" },
  { num: 233, track: "Action Track USA", url: "https://youtu.be/txaAXjX0Fsw" },
  { num: 234, track: "Lanco", url: "https://youtu.be/8mQBrGss59k234" },
  { num: 235, track: "Lanco", url: "https://youtu.be/_HQIs2jbrlY" },
  { num: 236, track: "Lanco", url: "https://youtu.be/gXbKKD3ijeU" },
  { num: 242, track: "Huset's Speedway", url: "https://youtu.be/y6jhP8ExGAg" },
  { num: 243, track: "Huset's Speedway", url: "https://youtu.be/B5Hm5_xxItA" },
  { num: 244, track: "Huset's Speedway", url: "https://youtu.be/fv3YsBS25rQ" },
  { num: 245, track: "Huset's Speedway", url: "https://youtu.be/LoCmHwDYtKs" },
  { num: 246, track: "Huset's Speedway", url: "https://youtu.be/9zPX3AncZaM" },
  { num: 246, track: "Huset's Speedway", url: "https://youtu.be/gwtxNvxleQc" },
  { num: 247, track: "Huset's Speedway", url: "https://youtu.be/xWSclvr5i5w" },
  { num: 252, track: "Arizona Speedway", url: "https://youtu.be/sCLj5vQGiDU" },
  { num: 254, track: "Arizona Speedway", url: "https://youtu.be/Q5ZcjRDbNYo" },
  { num: 255, track: "Wild Horse Pass", url: "https://youtu.be/aMzaQzdxvl8" },
  { num: 256, track: "Arizona Speedway", url: "https://youtu.be/_Jg-r3UbkbE" },
  { num: 257, track: "Arizona Speedway", url: "https://youtu.be/bfQmKmaSxIw" },
  { num: 258, track: "Wild Horse Pass", url: "https://youtu.be/r12Wjt8fH3c" },
  { num: 259, track: "Perris Auto Speedway", url: "https://youtu.be/vBIPVuflF8Y" },
  { num: 260, track: "Perris Auto Speedway", url: "https://youtu.be/N8WYnpkgVLs" },
  { num: 261, track: "Perris Auto Speedway", url: "https://youtu.be/O-W6sXP-EEs" },
  { num: 262, track: "Gateway Dirt Nationals (Qualifying)", url: "https://youtu.be/d5iDvgQK87A" },
  { num: 263, track: "Gateway Dirt Nationals", url: "https://youtu.be/3HrQXGKErmM" },
  { num: 264, track: "Gateway Dirt Nationals", url: "https://youtu.be/r5hEVqnGvSs" },
  { num: 265, track: "Gateway Dirt Nationals", url: "https://youtu.be/9bW9mTRB0dY" },
  { num: 266, track: "Cocopah Speedway", url: "https://youtu.be/ku8buT27au4" },
  { num: 268, track: "Cocopah Speedway", url: "https://youtu.be/Gbb4kggVG2w" },
  { num: 271, track: "Cocopah Speedway", url: "https://youtu.be/6poYAyu3tac" },
  { num: 272, track: "Cocopah Speedway", url: "https://youtu.be/v6dxAKz2x2I" },
  { num: 277, track: "Skagit Speedway", url: "https://youtu.be/7f2qRhRnQRY" },
  { num: 278, track: "Skagit Speedway", url: "https://youtu.be/vcJHQkUny44" },
  { num: 279, track: "Skagit Speedway", url: "https://youtu.be/EX1a4lO4kFQ" },
  { num: 280, track: "Skagit Speedway", url: "https://youtu.be/EX1a4lO4kFQ" },
  { num: 281, track: "Skagit Speedway", url: "https://youtu.be/EX1a4lO4kFQ" },
  { num: 282, track: "Skagit Speedway", url: "https://youtu.be/DZget9kSkrI" },
  { num: 283, track: "Skagit Speedway", url: "https://youtu.be/GSBRCfsUIvw" },
  { num: 286, track: "Greenwood Valley Action Track", url: "https://youtu.be/tdu3jPTic28" },
  { num: 287, track: "Greenwood Valley Action Track", url: "https://youtu.be/eNbcKczzERU" },
  { num: 288, track: "Greenwood Valley Action Track", url: "https://youtu.be/h-5stwwXJ6E" },
  { num: 289, track: "Spirit Auto Center Speedway", url: "https://youtu.be/rLhT4J6sADE" },
  { num: 290, track: "Action Track USA", url: "https://youtu.be/7JV8p5fWBAg" },
  { num: 294, track: "Linda's Speedway", url: "https://youtu.be/FCPN4pDk5SE" },
  { num: 295, track: "Linda's Speedway", url: "https://youtu.be/qlxG9AsBNsM" },
  { num: 298, track: "Gas City (Hot Laps)", url: "https://youtu.be/4kswLpMLBF4" },
  { num: 299, track: "Gas City (Qualifying)", url: "https://youtu.be/xoRbvtpEJzQ" },
  { num: 300, track: "Gas City (Qualifying)", url: "https://youtu.be/pIBlFa9WYj8" },
  { num: 301, track: "Gas City Speedway", url: "https://youtu.be/Auzd6UR_TYk" },
  { num: 302, track: "Gas City Speedway", url: "https://youtu.be/g2sLtG_cMoQ" },
  { num: 303, track: "Gas City Speedway", url: "https://youtu.be/O5FopRxJza8" },
  { num: 305, track: "Circle City Raceway", url: "https://youtu.be/wWv5L3K__NM" },
  { num: 307, track: "Kokomo Speedway (Qualifying)", url: "https://youtu.be/pHBB1BI_WbE" },
  { num: 308, track: "Kokomo Speedway", url: "https://youtu.be/LUqkfjRyD4M" },
  { num: 309, track: "Kokomo Speedway", url: "https://youtu.be/g3mr9YfJ7ss" },
  { num: 310, track: "Kokomo Speedway", url: "https://youtu.be/SD7Gce4o-eU" },
  { num: 311, track: "Bloomington Speedway", url: "https://youtu.be/NEwKd4SqgA8" },
  { num: 312, track: "Bloomington Speedway", url: "https://youtu.be/4L6OWQD05xw" },
  { num: 313, track: "Bloomington Speedway", url: "https://youtu.be/_Iy9avxSnA8" },
  { num: 319, track: "Dirt City Motorplex", url: "https://youtu.be/2KjHwbVh-Ek" },
  { num: 321, track: "Dirt City Motorplex", url: "https://youtu.be/j_EErV1ift8" },
  { num: 326, track: "Outlaw Speedway", url: "https://youtu.be/i5ML7u4eWxM" },
  { num: 327, track: "Albany-Saratoga Speedway", url: "https://youtu.be/UCpcNkKnPPw" },
  { num: 328, track: "Albany-Saratoga Speedway", url: "https://youtu.be/6598qo371Xg" },
  { num: 329, track: "I-30 Speedway", url: "https://youtu.be/2VN6gR0EZqQ" },
  { num: 330, track: "I-30 Speedway", url: "https://youtu.be/pD7pAc1gI4Q" },
  { num: 331, track: "I-30 Speedway", url: "https://youtu.be/pD7pAc1gI4Q" },
  { num: 332, track: "I-30 Speedway", url: "https://youtu.be/TWbOrIlHSHE" },
  { num: 333, track: "I-30 Speedway", url: "https://youtu.be/tfo7xL--fI4" },
  { num: 335, track: "Millbridge Speedway", url: "https://youtu.be/QJUtttdfH48" },
  { num: 336, track: "Millbridge Speedway", url: "https://youtu.be/mb_VgK6WDic" },
  { num: 337, track: "Glen Helen Raceway", url: "https://youtu.be/aNZseNfXUWU" },
  { num: 338, track: "Glen Helen Raceway", url: "https://youtu.be/xdLsXeTSxGU" },
  { num: 339, track: "Glen Helen Raceway", url: "https://youtu.be/dwPgHluafcg" },
  { num: 341, track: "Perris Auto Speedway", url: "https://youtu.be/HdwSjSsH-Hs" },
  { num: 342, track: "Perris Auto Speedway", url: "https://youtu.be/WdrOSUMKx_4" },
  { num: 345, track: "Wild Horse Pass", url: "https://youtu.be/pn8v-p7F1o4" },
  { num: 347, track: "Adobe Mountain Speedway", url: "https://youtu.be/fxrvDU1OJk4" },
  { num: 349, track: "Adobe Mountain Speedway", url: "https://youtu.be/wPD_2O4B1RY" },
  { num: 350, track: "Adobe Mountain Speedway", url: "https://youtu.be/gcUP_Vby7WI" },
  { num: 351, track: "Adobe Mountain Speedway", url: "https://youtu.be/aJ728RHWq1k" },
  { num: 352, track: "Wild Horse Pass", url: "https://youtu.be/Ni1jkX30NWc" },
  { num: 353, track: "Wild Horse Pass", url: "https://youtu.be/V31CEK3JxGc" },
  { num: 354, track: "Bakersfield Speedway", url: "https://youtu.be/4wYaOjh-oC8" },
  { num: 355, track: "Bakersfield Speedway", url: "https://youtu.be/7ggZyHIED0I" },
  { num: 357, track: "Bakersfield Speedway", url: "https://youtu.be/4sKuSiT51Q0" },
  { num: 358, track: "Bakersfield Speedway", url: "https://youtu.be/b3VBs1lqyZg" },
  { num: 359, track: "Gateway Dirt Nationals", url: "https://youtu.be/D0o__ZU0EgI" },
  { num: 360, track: "Gateway Dirt Nationals", url: "https://youtu.be/otBeyImSWAw" },
  { num: 361, track: "Gateway Dirt Nationals", url: "https://youtu.be/j4zjyu0T2ZA" },
  { num: 362, track: "Gateway Dirt Nationals", url: "https://youtu.be/jbgLOR0cbGs" },
  { num: 363, track: "Gateway Dirt Nationals", url: "https://youtu.be/-bj2tz3ukfw" },
  { num: 364, track: "Chili Bowl", url: "https://youtu.be/gVjSDeQJBkE" },
  { num: 365, track: "Chili Bowl", url: "https://youtu.be/-yfTkArljXo" },
  { num: 366, track: "Chili Bowl", url: "https://youtu.be/qgN7EFqvRA0" },
  { num: 367, track: "Chili Bowl", url: "https://youtu.be/xtbpROEkRHw" },
  { num: 368, track: "Chili Bowl", url: "https://youtu.be/xtbpROEkRHw" },
  { num: 369, track: "Chili Bowl", url: "https://youtu.be/r4paPuH9aVU" },
  { num: 370, track: "Chili Bowl", url: "https://youtu.be/a-w2OxlBp58" },
  { num: 371, track: "Chili Bowl", url: "https://youtu.be/a-w2OxlBp58" },
  { num: 372, track: "Chili Bowl", url: "https://youtu.be/gsV9eISBfNo" },
  { num: 373, track: "Chili Bowl", url: "https://youtu.be/-A8HO-jY3-Y" },
  { num: 374, track: "Chili Bowl", url: "https://youtu.be/sh8fPlLAyUs" },
  { num: 376, track: "Chili Bowl", url: "https://youtu.be/Fpqtj_sBLVA" },
  { num: 377, track: "Chili Bowl", url: "https://youtu.be/vsltb-tO-ZU" },
  { num: 378, track: "Chili Bowl", url: "https://youtu.be/BDhBGUcmkGk" },
  { num: 379, track: "Chili Bowl", url: "https://youtu.be/mLRpNaJuJXE" },
  { num: 380, track: "Chili Bowl", url: "https://youtu.be/JWrF6iS9vRw" },
  { num: 381, track: "Chili Bowl", url: "https://youtu.be/nVZ92bsQqsE" },
  { num: 382, track: "Chili Bowl", url: "https://youtu.be/ohlaMZI5z9I" },
  { num: 383, track: "Chili Bowl", url: "https://youtu.be/0fNtdqguEtA" },
  { num: 384, track: "Chili Bowl", url: "https://youtu.be/V0cG9uPEBeQ" },
  { num: 385, track: "Chili Bowl", url: "https://youtu.be/R5UTHhzyGPs" },
  { num: 386, track: "Chili Bowl", url: "https://youtu.be/eXHWji4ypC8" },
  { num: 387, track: "Chili Bowl", url: "https://youtu.be/vkHYbsdTMsA" },
  { num: 388, track: "Chili Bowl", url: "https://youtu.be/ggz7_O5gKGY" },
  { num: 389, track: "Chili Bowl", url: "https://youtu.be/leLXieCpNlI" },
  { num: 390, track: "Chili Bowl", url: "https://youtu.be/-ixDAujcRhI" },
  { num: 391, track: "Chili Bowl", url: "https://youtu.be/iKYCtPmy7cA" },
  { num: 392, track: "Chili Bowl", url: "https://youtu.be/obIVQYtoXcQ" },
  { num: 394, track: "Chili Bowl (Hot Laps)", url: "https://youtu.be/tz8qi0ii0wQ" },
  { num: 395, track: "Chili Bowl", url: "https://youtu.be/hr5qomcL7us" },
  { num: 396, track: "Chili Bowl", url: "https://youtu.be/pAG3j1SdBJM" },
  { num: 397, track: "Chili Bowl", url: "https://youtu.be/_TAglBeirFA" },
  { num: 398, track: "Chili Bowl", url: "https://youtu.be/DPYe-pC_zsk" },
  { num: 399, track: "Chili Bowl", url: "https://youtu.be/xxDIKL8vZqA" },
  { num: 400, track: "Chili Bowl", url: "https://youtu.be/lm6m_cpDwyQ" },
  { num: 401, track: "Chili Bowl", url: "https://youtu.be/gjcyxexwdgw" },
  { num: 402, track: "Chili Bowl", url: "https://youtu.be/xw-raTqbEEA" },
  { num: 403, track: "Chili Bowl", url: "https://youtu.be/nYV_ffrFDUU" },
  { num: 404, track: "Chili Bowl", url: "https://youtu.be/81I09Mdmvs4" },
  { num: 405, track: "Chili Bowl", url: "https://youtu.be/ZIDw8rWgemY" },
  { num: 407, track: "Chili Bowl", url: "https://youtu.be/KITiuSIL8vg" },
  { num: 408, track: "Chili Bowl", url: "https://youtu.be/hP2blh293BE" },
  { num: 409, track: "Chili Bowl", url: "https://youtu.be/VEvwUyk0j4Q" },
  { num: 410, track: "Chili Bowl", url: "https://youtu.be/_YJxCFIt7oQ" },
  { num: 411, track: "Chili Bowl", url: "https://youtu.be/ycQ39fafpeQ" },
  { num: 412, track: "Chili Bowl", url: "https://youtu.be/ycQ39fafpeQ" },
  { num: 413, track: "Chili Bowl", url: "https://youtu.be/ycQ39fafpeQ" },
  { num: 414, track: "Chili Bowl", url: "https://youtu.be/bOshog5KjO8" },
  { num: 415, track: "Chili Bowl", url: "https://youtu.be/I5gTFMGOTqQ" },
  { num: 416, track: "Chili Bowl", url: "https://youtu.be/I5gTFMGOTqQ" },
  { num: 417, track: "Chili Bowl", url: "https://youtu.be/NwOPwKRkvsE" },
  { num: 418, track: "Chili Bowl", url: "https://youtu.be/Gzv7aNIhC-8" },
  { num: 440, track: "Hendry County Speedway", url: "https://youtu.be/gjXh_1jn-Mk" },
  { num: 441, track: "Hendry County Speedway", url: "https://youtu.be/F78vhGVauvg" },
  { num: 442, track: "East Bay Raceway Park", url: "https://youtu.be/RLHHb-SfU1I" },
  { num: 443, track: "Volusia Speedway Park", url: "https://youtu.be/7lYeVxoNIB8" },
  { num: 444, track: "Bubba Raceway Park (Qualifying)", url: "https://youtu.be/PC90qMXKEWI" },
  { num: 445, track: "Daytona International Speedway", url: "https://youtu.be/VDEFunO9rEI" },
  { num: 446, track: "Accord Speedway", url: "https://youtu.be/JxJFSBQrGfQ" },
  { num: 448, track: "Clinton County Speedway", url: "https://youtu.be/Xmn_-iQ1DHc" },
  { num: 449, track: "Clinton County Speedway", url: "https://youtu.be/r0K6LH5mNUs" },
  { num: 450, track: "Bowman Gray Stadium", url: "https://youtu.be/ChQiaXpDvjU" },
  { num: 452, track: "Millbridge Speedway", url: "https://youtu.be/gT6wmQSUQXs" },
  { num: 453, track: "Millbridge Speedway", url: "https://youtu.be/M6MwUscXMN8" },
  { num: 454, track: "Millbridge Speedway", url: "https://youtu.be/0EIfhqKw5-M" },
  { num: 455, track: "Millbridge Speedway", url: "https://youtu.be/0EIfhqKw5-M" },
  { num: 456, track: "Bridgeport", url: "https://youtu.be/aaWKd-JDPUY" },
  { num: 459, track: "Grandview Speedway", url: "https://youtu.be/0etzP8MkzPo" },
  { num: 460, track: "Action Track USA", url: "https://youtu.be/uweJckktpD0" },
  { num: 461, track: "Action Track USA", url: "https://youtu.be/aZ5Asslg_kI" },
  { num: 462, track: "Macon Speedway", url: "https://youtu.be/GyE4YnGSlMI" },
  { num: 463, track: "Macon Speedway", url: "https://youtu.be/K712UQf9huQ" },
  { num: 464, track: "Macon Speedway", url: "https://youtu.be/rUOUaxyA_O0" },
  { num: 466, track: "Macon Speedway", url: "https://youtu.be/K2rGHSUQyn8" },
  { num: 467, track: "Macon Speedway", url: "https://youtu.be/7PdY6SUXaPw" },
  { num: 468, track: "NHMS Flat Track", url: "https://youtu.be/sXHMwugWGYw" },
  { num: 470, track: "NHMS Flat Track", url: "https://youtu.be/J0neLXCTGKQ" },
  { num: 476, track: "Action Track USA", url: "https://youtu.be/KPRf31zC8ms" },
  { num: 477, track: "Action Track USA", url: "https://youtu.be/V_CSouGeLcY" },
  { num: 478, track: "Lanco (Qualifying)", url: "https://youtu.be/z5F29hFbHps" },
  { num: 479, track: "Lanco", url: "https://youtu.be/afTjETpap5E" },
  { num: 481, track: "Lanco", url: "https://youtu.be/fTnfUou_rtY" },
  { num: 482, track: "Lanco", url: "https://youtu.be/nJX_D_TXI08" },
  { num: 484, track: "Action Track USA", url: "https://youtu.be/pTmc6Hdd_Mg" },
  { num: 485, track: "Action Track USA", url: "https://youtu.be/I6WAbBff5Vw" },
  { num: 486, track: "Action Track USA", url: "https://youtu.be/uH7S28Vya44" },
  { num: 486, track: "Action Track USA", url: "https://youtu.be/_jgSNnqIDPE" },
  { num: 487, track: "Action Track USA", url: "https://youtu.be/_jgSNnqIDPE" },
  { num: 488, track: "Path Valley Speedway Park", url: "https://youtu.be/UFaZP-OEo48" },
  { num: 489, track: "Path Valley Speedway Park", url: "https://youtu.be/oWzRdhi2_w4" },
  { num: 490, track: "Path Valley Speedway Park", url: "https://youtu.be/E5CMHOP_WfQ" },
  { num: 491, track: "Devil's Bowl Speedway (TX)", url: "https://youtu.be/-4TTgOD0etU" },
  { num: 492, track: "Devil's Bowl Speedway (TX)", url: "https://youtu.be/-4TTgOD0etU" },
  { num: 493, track: "Stockton Dirt Track", url: "https://youtu.be/_E7yOYQc_gg" },
  { num: 494, track: "SBC Fairgrounds", url: "https://youtu.be/d4WoQU1iqRo" },
  { num: 497, track: "SBC Fairgrounds", url: "https://youtu.be/TD1qBF7d7NA" },
  { num: 498, track: "SBC Fairgrounds", url: "https://youtu.be/tcFTI27JF6w" },
  { num: 499, track: "Wild Horse Pass", url: "https://youtu.be/ZToStRlIrO4" },
  { num: 500, track: "Wild Horse Pass", url: "https://youtu.be/yJrR--V_cEg" },
  { num: 501, track: "Wild Horse Pass", url: "https://youtu.be/ESpuiqTLnGg" },
  { num: 502, track: "Wild Horse Pass", url: "https://youtu.be/Mnsl-QeALUk" },
  { num: 503, track: "Wild Horse Pass", url: "https://youtu.be/48rYrkAWRmY" },
  { num: 506, track: "Bakersfield Speedway", url: "https://youtu.be/FPISEIvh8HU" },
  { num: 507, track: "Bakersfield Speedway", url: "https://youtu.be/FPISEIvh8HU" },
  { num: 508, track: "Placerville Speedway", url: "https://youtu.be/1DtwQHrFEZM" },
  { num: 509, track: "Placerville Speedway", url: "https://youtu.be/au1VD2V3NOE" },
  { num: 510, track: "Placerville Speedway", url: "https://youtu.be/ORfQndgVtSk" },
  { num: 511, track: "Placerville Speedway", url: "https://youtu.be/xPdY1O2SHN4" },
  { num: 512, track: "Placerville Speedway", url: "https://youtu.be/hXsyvhqvVlc" },
  { num: 513, track: "Placerville Speedway", url: "https://youtu.be/hXsyvhqvVlc" },
  { num: 514, track: "Placerville Speedway", url: "https://youtu.be/-JdjHl4tJ-w" },
  { num: 515, track: "Placerville Speedway", url: "https://youtu.be/ZEAJWZl_ObE" },
  { num: 518, track: "Placerville Speedway", url: "https://youtu.be/aMpbT55AICI" },
  { num: 519, track: "Placerville Speedway", url: "https://youtu.be/aMpbT55AICI" },
  { num: 520, track: "Merced Raceway", url: "https://youtu.be/innSzTHPBQQ" },
  { num: 521, track: "Merced Raceway (Qualifying)", url: "https://youtu.be/btumeU4oQ_8" },
  { num: 522, track: "Merced Raceway", url: "https://youtu.be/tdy0K-lN-vc" },
  { num: 523, track: "Merced Raceway", url: "https://youtu.be/k2cQ8R9krnw" },
  { num: 524, track: "Merced Raceway", url: "https://youtu.be/OnYunRldwL0" },
  { num: 525, track: "Merced Raceway", url: "https://youtu.be/s3Zdnxrn3jE" },
  { num: 526, track: "Ventura Raceway", url: "https://youtu.be/D_nd52MdJZY" },
  { num: 527, track: "Ventura Raceway", url: "https://youtu.be/8LceqLfEDus" },
  { num: 528, track: "Ventura Raceway", url: "https://youtu.be/8LceqLfEDus" },
  { num: 529, track: "Ventura Raceway (Qualifying)", url: "https://youtu.be/4e8pMbULF7k" },
  { num: 530, track: "Ventura Raceway", url: "https://youtu.be/_pBXfbMUoMw" },
  { num: 531, track: "Ventura Raceway", url: "https://youtu.be/_pBXfbMUoMw" },
  { num: 533, track: "Gateway Dirt Nationals (Qualifying)", url: "https://youtu.be/JE4mZQUrLoM" },
  { num: 534, track: "Gateway Dirt Nationals", url: "https://youtu.be/iA_B2Y3ytmQ" },
  { num: 538, track: "East Bay Raceway Park", url: "https://youtu.be/NaM890aCGcI" },
  { num: 539, track: "East Bay Raceway Park", url: "https://youtu.be/PrYvXCxlNWE" },
  { num: 540, track: "East Bay Raceway Park", url: "https://youtu.be/PrYvXCxlNWE" },
  { num: 541, track: "East Bay Raceway Park", url: "https://youtu.be/-6-IYjobKrY" },
  { num: 542, track: "East Bay Raceway Park", url: "https://youtu.be/CMv2ijmm0dA" },
  { num: 543, track: "East Bay Raceway Park", url: "https://youtu.be/CMv2ijmm0dA" },
  { num: 544, track: "East Bay Raceway Park", url: "https://youtu.be/4rlYq_AJHGE" },
  { num: 545, track: "East Bay Raceway Park", url: "https://youtu.be/rd1oj-X5OKY" },
  { num: 546, track: "Daytona International Speedway", url: "https://youtu.be/DpBxFqaiSTY" },
  { num: 548, track: "Nitrodome At Planet Hollywod", url: "https://youtu.be/pZeW2tdMQ7A" },
  { num: 552, track: "Sweet Springs Motorsports Complex", url: "https://youtu.be/b_arqrVV2P4" },
  { num: 553, track: "Sweet Springs Motorsports Complex", url: "https://youtu.be/hoiPRQyQorE" },
  { num: 554, track: "Action Track USA", url: "https://youtu.be/2Q-6KZ4ufjI" },
  { num: 556, track: "Big Diamond Speedway", url: "https://youtu.be/-BGfQFEAMqU" },
  { num: 557, track: "William's Grove Speedway", url: "https://youtu.be/LctEh-O9hJo" },
  { num: 562, track: "Humberstone Speedway", url: "https://youtu.be/8aP5XogXIpQ" },
  { num: 563, track: "Lincoln Park Raceway (Qualifying)", url: "https://youtu.be/JzP68GrTIIg" },
  { num: 564, track: "Lincoln Park Speedway", url: "https://youtu.be/Dt4TawxSvhc" },
  { num: 565, track: "Lincoln Park Speedway", url: "https://youtu.be/XWdsdm741gw" },
  { num: 567, track: "Lincoln Park Speedway", url: "https://youtu.be/zgXxKf4Ks_c" },
  { num: 568, track: "Kokomo Speedway", url: "https://youtu.be/PA1k7HZa2eg" },
  { num: 569, track: "Kokomo Speedway", url: "https://youtu.be/_XU12Ac0uhQ" },
  { num: 570, track: "Lawrenceburg Speedway", url: "https://youtu.be/AJrGl1o5Uz0" },
  { num: 571, track: "Lawrenceburg Speedway", url: "https://youtu.be/h_OK-j2rbjE" },
  { num: 572, track: "Lawrenceburg Speedway", url: "https://youtu.be/h_OK-j2rbjE" },
  { num: 573, track: "Lawrenceburg Speedway", url: "https://youtu.be/rCu9jvwkZzA" },
  { num: 574, track: "Circle City Raceway", url: "https://youtu.be/O1SPJ-D673E" },
  { num: 575, track: "Circle City Raceway", url: "https://youtu.be/9GZavkWmY2A" },
  { num: 576, track: "Circle City Raceway", url: "https://youtu.be/qIQAjzhzsfk" },
  { num: 577, track: "Bloomington Raceway", url: "https://youtu.be/QpCHkLIG4VU" },
  { num: 578, track: "Bloomington Raceway", url: "https://youtu.be/QpCHkLIG4VU" },
  { num: 579, track: "Federated Auto Parts Raceway at I-55 (Qualifying)", url: "https://youtu.be/Uz8EhyGNON0" },
  { num: 582, track: "Federated Auto Parts Raceway at I-55", url: "https://youtu.be/Y-KaL6Lqwm8" },
  { num: 583, track: "Federated Auto Parts Raceway at I-55", url: "https://youtu.be/3RH9Lbg8N9g" },
  { num: 584, track: "Bloomington Speedway", url: "https://youtu.be/mYs3ime09O8" },
  { num: 585, track: "Bloomington Speedway", url: "https://youtu.be/OMgb4q4_gIg" },
  { num: 586, track: "Bloomington Speedway", url: "https://youtu.be/aZLnIvVcQtA" },
  { num: 587, track: "MX101", url: "https://youtu.be/8AatX3fR2BQ" },
  { num: 588, track: "Angell Park Speedway", url: "https://youtu.be/TMyavuusKok" },
  { num: 590, track: "Tulare Thunderbowl Speedway", url: "https://youtu.be/CaaE_d7QfWg" },
  { num: 591, track: "Tulare Thunderbowl Speedway", url: "https://youtu.be/BkcG7pY739s" },
  { num: 592, track: "Tulare Thunderbowl Speedway", url: "https://youtu.be/43A6qY_tLew" },
  { num: 593, track: "Merced Speedway (Qualifying)", url: "https://youtu.be/_o2bvWD6mvE" },
  { num: 594, track: "Merced Speedway (Qualifying)", url: "https://youtu.be/9EAWxI2PHt0" },
  { num: 595, track: "Merced Speedway", url: "https://youtu.be/ETPpqCxaS7Q" },
  { num: 596, track: "Merced Speedway", url: "https://youtu.be/hgz2pBpdNUg" },
  { num: 597, track: "Merced Speedway", url: "https://youtu.be/GHR91klDvtI" },
  { num: 602, track: "Bakersfield Speedway (Hot Laps)", url: "https://youtu.be/V9ir3XoXc80" },
  { num: 603, track: "Bakersfield Speedway", url: "https://youtu.be/GBDGItGy1qA" },
  { num: 604, track: "Bakersfield Speedway", url: "https://youtu.be/_pfKyN990KQ" },
  { num: 605, track: "Bakersfield Speedway", url: "https://youtu.be/EVGbFtce_7U" },
  { num: 606, track: "Bakersfield Speedway", url: "https://youtu.be/Pb5iYAt_pto" },
  { num: 607, track: "Bakersfield Speedway", url: "https://youtu.be/H0zeRF4_Zr4" },
  { num: 608, track: "Ventura Raceway", url: "https://youtu.be/V5Pi7w8Sy7U" },
  { num: 609, track: "Ventura Raceway (Practice)", url: "https://youtu.be/mep4R0741yM" },
  { num: 610, track: "Ventura Raceway (Practice)", url: "https://youtu.be/O12N3tsPKuw" },
  { num: 612, track: "Ventura Raceway", url: "https://youtu.be/6Ppu-6g3KFM" },
  { num: 614, track: "Ventura Raceway", url: "https://youtu.be/3n5G9GF2P0M" },
  { num: 615, track: "Gateway Dirt Nationals", url: "https://youtu.be/B2cYCKM6cDw" },
  { num: 616, track: "PPL Center", url: "https://youtu.be/N38cpqYlY6k" },
  { num: 617, track: "PPL Center", url: "https://youtu.be/78HTJzL-Cew" },
  { num: 619, track: "Ocala Raceway", url: "https://youtu.be/MnTGvoJi8Rc" },
  { num: 621, track: "Ocala Raceway", url: "https://youtu.be/pf-6FGUuVjs" },
  { num: 622, track: "Daytona International Speedway", url: "https://youtu.be/E39He8PirGA" },
  { num: 624, track: "Albany-Saratoga Speedway (Hot Laps)", url: "https://youtube.com/shorts/WlSyVhJqW-I" },
  { num: 625, track: "Bloomington Speedway", url: "https://youtu.be/8lRWJ2QPlCE" },
  { num: 626, track: "Bloomington Speedway", url: "https://youtu.be/DUrfhmPXQMM" },
  { num: 628, track: "Kokomo Speedway", url: "https://youtu.be/EG1BG_3H3kc" },
  { num: 629, track: "Kokomo Speedway", url: "https://youtu.be/sJyLnEqptuw" },
  { num: 630, track: "Kokomo Speedway", url: "https://youtu.be/sJyLnEqptuw" },
  { num: 631, track: "Kokomo Speedway", url: "https://youtu.be/BjgQNYA5ngk" },
  { num: 633, track: "Atomic Speedway", url: "https://youtu.be/uZtrM6ryZD0" },
  { num: 635, track: "Action Track USA", url: "https://youtu.be/tSMgi5pNsrs" },
  { num: 636, track: "Action Track USA", url: "https://youtu.be/p1gN7szpq-s" },
  { num: 637, track: "Action Track USA", url: "https://youtu.be/bv5b23yu5sU" },
  { num: 639, track: "Bridgeport Motorsports Park", url: "https://youtu.be/v8xPj60KQr4" },
  { num: 644, track: "Port Royal Speedway", url: "https://youtu.be/Hai815kEVpM" },
  { num: 645, track: "Port Royal Speedway", url: "https://youtu.be/YD2dElakjA8" },
  { num: 646, track: "Port Royal Speedway", url: "https://youtu.be/YD2dElakjA8" },
  { num: 647, track: "Action Track USA", url: "https://youtu.be/8Qt4w8D3pIA" },
  { num: 648, track: "Action Track USA", url: "https://youtu.be/A5IGDwRid90" },
  { num: 649, track: "Action Track USA", url: "https://youtu.be/CEWYz2bbW74" },
  { num: 650, track: "Action Track USA", url: "https://youtu.be/6X6wtoV3I9Y" },
  { num: 651, track: "Action Track USA", url: "https://youtu.be/6X6wtoV3I9Y" },
  { num: 652, track: "Action Track USA", url: "https://youtu.be/6X6wtoV3I9Y" },
  { num: 653, track: "Action Track USA", url: "https://youtu.be/kcpXDx0XEYc" },
  { num: 655, track: "Millstream Speedway", url: "https://youtu.be/CuLJAdXTW9c" },
  { num: 657, track: "IMS Dirt Track", url: "https://youtu.be/mTswLpNzHuU" },
  { num: 658, track: "Lincoln Park Speedway", url: "https://youtu.be/H7Ee9ZYQMFc" },
  { num: 660, track: "Lawrenceburg Speedway", url: "https://youtu.be/co3cr3NACNc" },
  { num: 661, track: "Lawrenceburg Speedway", url: "https://youtu.be/co3cr3NACNc" },
  { num: 662, track: "Lawrenceburg Speedway", url: "https://youtu.be/co3cr3NACNc" },
  { num: 664, track: "Kokomo Speedway", url: "https://youtu.be/6nccy67xfjM" },
  { num: 665, track: "Kokomo Speedway", url: "https://youtu.be/k8B4yiEWhA0" },
  { num: 667, track: "Circle City Raceway (Qualifying)", url: "https://youtu.be/xO4WObMq2Hk" },
  { num: 668, track: "Terre Haute Action Track (Qualifying)", url: "https://youtu.be/KuGarY6tgF4" },
  { num: 669, track: "Terre Haute Action Track", url: "https://youtu.be/Mj2xB4CBLao" },
  { num: 670, track: "Albany-Saratoga Speedway", url: "https://youtu.be/oLJAzuZgjOw" },
  { num: 671, track: "Albany-Saratoga Speedway", url: "https://youtu.be/ici05w6YN7s" },
  { num: 673, track: "Hawkeye Downs Speedway Dirt", url: "https://youtu.be/uWAlNH2dVX0" },
  { num: 674, track: "Bridgeport Motorsports Park", url: "https://youtu.be/4HiD2hQCfQo" },
  { num: 677, track: "Placerville Speedway", url: "https://youtu.be/cnPFZ4SHN1s" },
  { num: 678, track: "Placerville Speedway", url: "https://youtu.be/Shdp9Fp0L70" },
  { num: 679, track: "Placerville Speedway", url: "https://youtu.be/L8xLsRuPX4Q" },
  { num: 680, track: "Placerville Speedway", url: "https://youtu.be/eJOhdCoKnTU" },
  { num: 681, track: "Placerville Speedway", url: "https://youtu.be/SGYFD_sDRCY" },
  { num: 682, track: "Placerville Speedway", url: "https://youtu.be/a5O_mEJY9XQ" },
  { num: 683, track: "Placerville Speedway", url: "https://youtu.be/osqfUgX2qL4" },
  { num: 684, track: "Placerville Speedway", url: "https://youtu.be/bDz27wbZwZU" },
  { num: 685, track: "Placerville Speedway", url: "https://youtu.be/ptkprjztrLA" },
  { num: 688, track: "Placerville Speedway", url: "https://youtu.be/Tm6CZQV4HM4" },
  { num: 690, track: "Merced Speedway", url: "https://youtube.com/shorts/yv2fHGZ4_98" },
  { num: 691, track: "Merced Speedway (Qualifying)", url: "https://youtu.be/DNXfOnUnY50" },
  { num: 692, track: "Merced Speedway", url: "https://youtu.be/njCrLvDsPoc" },
  { num: 693, track: "Merced Speedway", url: "https://youtu.be/SF1Y5_WmMUc" },
  { num: 694, track: "Merced Speedway", url: "https://youtu.be/SF1Y5_WmMUc" },
  { num: 695, track: "Merced Speedway", url: "https://youtu.be/hNiEu7lXLT4" },
  { num: 696, track: "Merced Speedway", url: "https://youtu.be/Fez235eSy5c" },
  { num: 698, track: "Kern County Dirt Track (Qualifying)", url: "https://youtu.be/tK1YdI-VTMg" },
  { num: 699, track: "Kern County Dirt Track (Hot Laps)", url: "https://youtu.be/5ZRnnx4SRyY" },
  { num: 701, track: "Ventura Raceway (Group Qualifying)", url: "https://youtu.be/ZjbNsU5vkjo" },
  { num: 706, track: "Ventura Raceway", url: "https://youtu.be/xPfIcmJ7WRw" },
  { num: 707, track: "Ventura Raceway", url: "https://youtu.be/xS1G_ZrsjJY" },
  { num: 708, track: "Ventura Raceway", url: "https://youtu.be/f2vbh_kaCV4" },
  { num: 711, track: "Ventura Raceway", url: "https://youtu.be/eCM4J2wLnpE" },
  { num: 712, track: "Ventura Raceway", url: "https://youtu.be/RivD7pvrVXs" },
  { num: 713, track: "Ventura Raceway", url: "https://youtube.com/shorts/DfaZFRBUPwc" },
  { num: 715, track: "Ventura Raceway", url: "https://youtu.be/8yXl850StxU" },
  { num: 716, track: "Ventura Raceway", url: "https://youtu.be/7LQ_lCF1nXM" },
  { num: 717, track: "Ventura Raceway", url: "https://youtu.be/-f3KFy0sktE" },
  { num: 718, track: "Gateway Dirt Nationals", url: "https://youtu.be/HXiJfaBgLa0" },
  { num: 719, track: "Chili Bowl", url: "https://youtu.be/cnKAcKSGMPA" },
  { num: 721, track: "Chili Bowl", url: "https://youtu.be/MIuKzpsAFhw" },
  { num: 722, track: "Chili Bowl", url: "https://youtu.be/nsXbHwdblug" },
  { num: 723, track: "Chili Bowl", url: "https://youtu.be/y_DPS-mouxE" },
  { num: 724, track: "Chili Bowl", url: "https://youtu.be/96GkPNaDJCs" },
  { num: 725, track: "Chili Bowl", url: "https://youtu.be/oYEllJC4P68" },
  { num: 726, track: "Chili Bowl", url: "https://youtu.be/J9wtkY9PzD8" },
  { num: 727, track: "Chili Bowl", url: "https://youtu.be/L8i5nPckMFc" },
  { num: 728, track: "Chili Bowl", url: "https://youtu.be/zEYH4bp3zb4" },
  { num: 729, track: "Chili Bowl", url: "https://youtu.be/JhpBJz-hHpE" },
  { num: 730, track: "Chili Bowl", url: "https://youtu.be/Q-h4ypDqTEU" },
  { num: 731, track: "Chili Bowl", url: "https://youtu.be/1vekAt2Ba2M" },
  { num: 732, track: "Chili Bowl (Hot Laps)", url: "https://youtu.be/566z3xRJNq8" },
  { num: 733, track: "Chili Bowl", url: "https://youtu.be/P94lSRMEdtE" },
  { num: 734, track: "Chili Bowl", url: "https://youtu.be/_cU9qmJNby4" },
  { num: 740, track: "Cure Insurance Arena", url: "https://youtu.be/ybQHrSyHtlU" },
  { num: 741, track: "Cure Insurance Arena", url: "https://youtube.com/shorts/PeEB_dwg-Qk" },
];
